name: C/C++ CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  release:
    types: [published]

jobs:
  linux:
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            os-name: Linux
            arch-name: 64bit
          - runner: ubuntu-24.04-arm
            os-name: Linux
            arch-name: ARM64
    runs-on: ${{ matrix.runner }}
    env:
      package_name: ncpatcher_${{ github.ref_name }}_${{ matrix.os-name }}-${{ matrix.arch-name }}
    steps:
    - uses: actions/checkout@v6
    - name: Build package
      run: |
        mkdir build
        cd build
        cmake ../ -DCMAKE_BUILD_TYPE=Release -DMAKE_PACK=ON
        make -j$(nproc)
        mv ncpatcher_pack ../$package_name
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        path: ${{ env.package_name }}
        name: ${{ env.package_name }}
    - name: Compress package
      if: ${{ success() && startsWith(github.ref, 'refs/tags') }}
      run: tar -cvzf $package_name.tgz $package_name
    - name: Upload to release
      if: ${{ success() && startsWith(github.ref, 'refs/tags') }}
      uses: AButler/upload-release-assets@v3.0
      with:
        files: ${{ env.package_name }}.tgz
        repo-token: ${{ secrets.GITHUB_TOKEN }}

  macos:
    strategy:
      matrix:
        include:
          - runner: macos-15-intel
            os-name: macOS
            arch-name: 64bit
          - runner: macos-15
            os-name: macOS
            arch-name: ARM64
    runs-on: ${{ matrix.runner }}
    env:
      package_name: ncpatcher_${{ github.ref_name }}_${{ matrix.os-name }}-${{ matrix.arch-name }}
    steps:
    - uses: actions/checkout@v6
    - name: Build package
      run: |
        mkdir build
        cd build
        cmake ../ -DCMAKE_BUILD_TYPE=Release -DMAKE_PACK=ON
        make -j$(nproc)
        mv ncpatcher_pack ../$package_name
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        path: ${{ env.package_name }}
        name: ${{ env.package_name }}
    - name: Compress package
      if: ${{ success() && startsWith(github.ref, 'refs/tags') }}
      run: tar -cvzf $package_name.tgz $package_name
    - name: Upload to release
      if: ${{ success() && startsWith(github.ref, 'refs/tags') }}
      uses: AButler/upload-release-assets@v3.0
      with:
        files: ${{ env.package_name }}.tgz
        repo-token: ${{ secrets.GITHUB_TOKEN }}

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - cmake-arch: x64
            arch-name: 64bit
          - cmake-arch: Win32
            arch-name: 32bit
          - cmake-arch: ARM64
            arch-name: ARM64
    env:
      package_name: ncpatcher_${{ github.ref_name }}_Windows-${{ matrix.arch-name }}
    steps:
    - uses: actions/checkout@v6
    - name: Build package
      run: |
        mkdir build
        cd build
        cmake ../ -G "Visual Studio 17 2022" -A ${{ matrix.cmake-arch }} -DMAKE_PACK=ON
        cmake --build . --config Release
        move ncpatcher_pack ..\${{ env.package_name }}
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        path: ${{ env.package_name }}
        name: ${{ env.package_name }}
    - name: Compress package
      if: ${{ success() && startsWith(github.ref, 'refs/tags') }}
      shell: powershell
      run: tar -a -c -f "$env:package_name.zip" "$env:package_name"
    - name: Upload to release
      if: ${{ success() && startsWith(github.ref, 'refs/tags') }}
      uses: AButler/upload-release-assets@v3.0
      with:
        files: ${{ env.package_name }}.zip
        repo-token: ${{ secrets.GITHUB_TOKEN }}
